perona = {}
---@return table
perona.build = function()
	local theme = {
		Normal = {fg = "#F4B9DC", bg = "#281520"},
		["@boolean"] = {link = "Boolean"},
		Character = {fg = "#DE91DA"},
		Boolean = {link = "Character"},
		Float = {link = "Character"},
		Number = {link = "Character"},
		["@character"] = {link = "Character"},
		ColorColumn = {bg = "#532742"},
		Comment = {fg = "#90647F", italic = true},
		LspCodeLens = {link = "Comment"},
		LspCodeLensSeparator = {link = "Comment"},
		["@comment"] = {link = "Comment"},
		["@text.literal"] = {link = "Comment"},
		Conceal = {fg = "#90647F"},
		["@conditional"] = {link = "Conditional"},
		Constant = {fg = "#74BE9E"},
		["@constant"] = {link = "Constant"},
		CurSearch = {fg = "#532742", bg = "#B4CFF8"},
		IncSearch = {link = "CurSearch"},
		Cursor = {fg = "#281520", bg = "#F4B9DC"},
		CursorIM = {link = "Cursor"},
		WildMenu = {link = "Cursor"},
		lCursor = {link = "Cursor"},
		CursorColumn = {bg = "#3E1D31"},
		CursorLine = {link = "CursorColumn"},
		CursorLineNr = {fg = "#8DAFE2", bg = "#3E1D31", bold = true},
		["@debug"] = {link = "Debug"},
		["@constant.macro"] = {link = "Define"},
		["@define"] = {link = "Define"},
		Delimiter = {fg = "#F47CB8"},
		["@punctuation"] = {link = "Delimiter"},
		DiagnosticError = {fg = "#DE3557"},
		DiagnosticFloatingError = {link = "DiagnosticError"},
		DiagnosticSignError = {link = "DiagnosticError"},
		DiagnosticVirtualTextError = {link = "DiagnosticError"},
		DiagnosticHint = {fg = "#DE91DA"},
		DiagnosticFloatingHint = {link = "DiagnosticHint"},
		DiagnosticSignHint = {link = "DiagnosticHint"},
		DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
		DiagnosticInfo = {fg = "#FF99CC"},
		DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
		DiagnosticSignInfo = {link = "DiagnosticInfo"},
		DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
		DiagnosticOk = {fg = "#74BE9E"},
		DiagnosticFloatingOk = {link = "DiagnosticOk"},
		DiagnosticSignOk = {link = "DiagnosticOk"},
		DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
		DiagnosticUnderlineError = {fg = "#DE3557", underline = true},
		DiagnosticUnderlineHint = {fg = "#DE91DA", underline = true},
		DiagnosticUnderlineInfo = {fg = "#FF99CC", underline = true},
		DiagnosticUnderlineOk = {fg = "#74BE9E", underline = true},
		DiagnosticUnderlineWarn = {fg = "#EB8490", underline = true},
		DiagnosticWarn = {fg = "#EB8490"},
		DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
		DiagnosticSignWarn = {link = "DiagnosticWarn"},
		DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
		DiffAdd = {fg = "#281520", bg = "#DE91DA", bold = true},
		DiffChange = {fg = "#F8D3E9", bg = "#683152", bold = true},
		DiffDelete = {fg = "#DE3557", bg = "#281520", bold = true},
		DiffText = {fg = "#281520", bg = "#8DAFE2"},
		Directory = {fg = "#D65C85"},
		EndOfBuffer = {fg = "#90647F"},
		Error = {fg = "#F8D3E9", bg = "#A90F30"},
		ErrorMsg = {fg = "#DE3557", bg = "#3E1D31"},
		["@exception"] = {link = "Exception"},
		["@float"] = {link = "Float"},
		FloatTitle = {fg = "#F4B9DC", bold = true},
		FoldColumn = {fg = "#683152"},
		CursorLineFold = {link = "FoldColumn"},
		CursorLineSign = {link = "FoldColumn"},
		SignColumn = {link = "FoldColumn"},
		Folded = {fg = "#F4B9DC", bg = "#24141E"},
		Function = {fg = "#8DAFE2"},
		["@function"] = {link = "Function"},
		["@method"] = {link = "Function"},
		Identifier = {fg = "#D65C85"},
		["@field"] = {link = "Identifier"},
		["@namespace"] = {link = "Identifier"},
		["@parameter"] = {link = "Identifier"},
		["@property"] = {link = "Identifier"},
		["@text.reference"] = {link = "Identifier"},
		["@variable"] = {link = "Identifier"},
		Ignore = {fg = "#B1819E"},
		Search = {link = "IncSearch"},
		["@include"] = {link = "Include"},
		["@keyword"] = {link = "Keyword"},
		["@label"] = {link = "Label"},
		LineNr = {fg = "#21121B", bg = "#B54067"},
		LineNrAbove = {link = "LineNr"},
		LineNrBelow = {link = "LineNr"},
		["@function.macro"] = {link = "Macro"},
		["@macro"] = {link = "Macro"},
		MatchParen = {fg = "#683152", bg = "#8DAFE2", bold = true},
		ModeMsg = {fg = "#F47CB8"},
		MoreMsg = {fg = "#683152"},
		MsgArea = {fg = "#B1819E"},
		MsgSeparator = {fg = "#281520", bg = "#B1819E"},
		NonText = {fg = "#90647F"},
		NormalFloat = {fg = "#B1819E", bg = "#24141E"},
		FloatBorder = {link = "NormalFloat"},
		NormalNC = {fg = "#90647F"},
		["@number"] = {link = "Number"},
		Operator = {fg = "#F47CB8"},
		["@operator"] = {link = "Operator"},
		Pmenu = {fg = "#F4B9DC", bg = "#24141E"},
		PmenuExtra = {link = "Pmenu"},
		PmenuKind = {link = "Pmenu"},
		PmenuSbar = {link = "Pmenu"},
		PmenuSel = {fg = "#24141E", bg = "#F4B9DC"},
		PmenuExtraSel = {link = "PmenuSel"},
		PmenuKindSel = {link = "PmenuSel"},
		PmenuThumb = {fg = "#F8D3E9", bg = "#90647F"},
		PreProc = {fg = "#EB8490"},
		Define = {link = "PreProc"},
		Include = {link = "PreProc"},
		Macro = {link = "PreProc"},
		PreCondit = {link = "PreProc"},
		["@preproc"] = {link = "PreProc"},
		Question = {fg = "#FF99CC"},
		QuickFixLine = {link = "Question"},
		RenderMarkdownH1Bg = {fg = "#281520", bg = "#F47CB8"},
		RenderMarkdownH2Bg = {fg = "#8DAFE2", bg = "#3E1D31"},
		RenderMarkdownH3Bg = {fg = "#EB8490", bg = "#3E1D31"},
		RenderMarkdownH4Bg = {fg = "#A90F30", bg = "#3E1D31"},
		RenderMarkdownH5Bg = {fg = "#74BE9E", bg = "#3E1D31"},
		RenderMarkdownH6Bg = {fg = "#A75FB4", bg = "#3E1D31"},
		["@repeat"] = {link = "Repeat"},
		Special = {fg = "#8DAFE2"},
		Debug = {link = "Special"},
		SpecialComment = {link = "Special"},
		Tag = {link = "Special"},
		["@constant.builtin"] = {link = "Special"},
		["@constructor"] = {link = "Special"},
		["@function.builtin"] = {link = "Special"},
		SpecialChar = {fg = "#DE91DA"},
		["@character.special"] = {link = "SpecialChar"},
		["@string.escape"] = {link = "SpecialChar"},
		["@string.special"] = {link = "SpecialChar"},
		SpecialKey = {fg = "#B1819E"},
		SpellBad = {fg = "#E65667", undercurl = true},
		SpellCap = {fg = "#EB8490", undercurl = true},
		SpellLocal = {fg = "#74BE9E", undercurl = true},
		SpellRare = {fg = "#B4CFF8", undercurl = true},
		Statement = {fg = "#B4CFF8", bold = true},
		Conditional = {link = "Statement"},
		Exception = {link = "Statement"},
		Keyword = {link = "Statement"},
		Label = {link = "Statement"},
		Repeat = {link = "Statement"},
		StatusLine = {bg = "#532742"},
		StatusLineNC = {bg = "#3E1D31"},
		["@storageclass"] = {link = "StorageClass"},
		String = {fg = "#FF99CC"},
		["@string"] = {link = "String"},
		["@structure"] = {link = "Structure"},
		Substitute = {fg = "#8DAFE2", bg = "#683152"},
		TabLine = {fg = "#90647F", bg = "#24141E"},
		TabLineFill = {bg = "#21121B"},
		TabLineSel = {fg = "#281520", bg = "#F47CB8", italic = true},
		["@tag"] = {link = "Tag"},
		TermCursor = {fg = "#281520", bg = "#B1819E"},
		TermCursorNC = {fg = "#B1819E"},
		Title = {bold = true},
		["@text.title"] = {link = "Title"},
		Todo = {bold = true},
		["@text.todo"] = {link = "Todo"},
		Type = {fg = "#F47CB8"},
		StorageClass = {link = "Type"},
		Structure = {link = "Type"},
		Typedef = {link = "Type"},
		["@type"] = {link = "Type"},
		["@type.definition"] = {link = "Typedef"},
		Underlined = {underline = true},
		["@text.underline"] = {link = "Underlined"},
		["@text.uri"] = {link = "Underlined"},
		VertSplit = {fg = "#3E1D31"},
		Winseparator = {link = "VertSplit"},
		Visual = {fg = "#281520", bg = "#F47CB8"},
		LspReferenceRead = {link = "Visual"},
		LspReferenceText = {link = "Visual"},
		LspReferenceWrite = {link = "Visual"},
		LspSignatureActiveParameter = {link = "Visual"},
		VisualNOS = {fg = "#281520", bg = "#B54067"},
		WarningMsg = {fg = "#EB8490"},
		Whitespace = {fg = "#683152"},
		WinBar = {bg = "#21121B", bold = true},
		WinBarNC = {bg = "#21121B"},
	}
	local opts = require("perona").opts
	if opts.transparent then
		theme["Normal"].bg = "none"
		theme["StatusLine"].bg = "none"
	end
	if opts.overrides ~= false then
					theme = vim.tbl_deep_extend("force", theme, opts.overrides)
	end
	return theme
end
return perona
