P = {}
---@return table
P.build = function()
  local theme = {
Normal = {fg = "#EFD2E3", bg = "#261720"},
["@boolean"] = {link = "Boolean"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#331F2B"},
Comment = {fg = "#AD859D", italic = true},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
Conceal = {fg = "#896C7D"},
["@keyword.conditional"] = {link = "Conditional"},
Constant = {fg = "#E28D8D"},
Boolean = {link = "Constant"},
Character = {link = "Constant"},
Float = {link = "Constant"},
Number = {link = "Constant"},
String = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
CurSearch = {fg = "#261720", bg = "#E28D8D"},
IncSearch = {link = "CurSearch"},
Cursor = {fg = "#261720", bg = "#EFD2E3"},
CursorIM = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#3F2735"},
CursorLine = {bg = "#3F2735"},
CursorLineNr = {fg = "#EFD2E3", bold = true},
["@constant.macro"] = {link = "Define"},
Delimiter = {fg = "#EFD2E3"},
DiagnosticDeprecated = {fg = "#896C7D", strikethrough = true},
DiagnosticError = {fg = "#D0435F"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#EA86C2"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#8DAFE2"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#D18DE2"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {fg = "#D0435F", undercurl = true},
DiagnosticUnderlineHint = {fg = "#EA86C2", undercurl = true},
DiagnosticUnderlineInfo = {fg = "#8DAFE2", undercurl = true},
DiagnosticUnderlineOk = {fg = "#D18DE2", undercurl = true},
DiagnosticUnderlineWarn = {fg = "#E28D8D", undercurl = true},
DiagnosticVirtualTextError = {fg = "#D0435F", italic = true},
DiagnosticVirtualTextHint = {fg = "#EA86C2", italic = true},
DiagnosticVirtualTextInfo = {fg = "#8DAFE2", italic = true},
DiagnosticVirtualTextOk = {fg = "#D18DE2", italic = true},
DiagnosticVirtualTextWarn = {fg = "#E28D8D", italic = true},
DiagnosticWarn = {fg = "#E28D8D"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#261720", bg = "#D18DE2"},
DiffChange = {fg = "#261720", bg = "#EA86C2"},
DiffDelete = {fg = "#D0435F", bold = true},
DiffText = {fg = "#261720", bg = "#8DAFE2"},
Directory = {fg = "#8DAFE2"},
EndOfBuffer = {fg = "#896C7D"},
Error = {fg = "#FFEBF7", bg = "#D0435F"},
ErrorMsg = {fg = "#D0435F", bold = true},
["@keyword.exception"] = {link = "Exception"},
["@number.float"] = {link = "Float"},
FloatBorder = {fg = "#896C7D", bg = "#331F2B"},
FloatFooter = {link = "FloatBorder"},
FloatTitle = {fg = "#EA86C2", bg = "#331F2B", bold = true},
FoldColumn = {fg = "#5F4554", bg = "#331F2B"},
Folded = {fg = "#AD859D", bg = "#31212A"},
Function = {fg = "#EA86C2"},
["@function"] = {link = "Function"},
["@function.method"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
Identifier = {fg = "#D65C8D"},
Ignore = {fg = "#896C7D"},
["@keyword.import"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@lsp.type.keyword"] = {link = "Keyword"},
LineNr = {fg = "#896C7D"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@function.macro"] = {link = "Macro"},
["@lsp.type.macro"] = {link = "Macro"},
MatchParen = {bg = "#5F4554", bold = true},
MiniDiffSignAdd = {fg = "#D18DE2", italic = true},
MiniDiffSignChange = {fg = "#EA86C2", italic = true},
MiniDiffSignDelete = {fg = "#D0435F", italic = true},
MiniStatuslineDevinfo = {fg = "#EFD2E3", bg = "#3F2735"},
MiniStatuslineFileinfo = {link = "MiniStatuslineDevinfo"},
MiniStatuslineFilename = {fg = "#AD859D", bg = "#331F2B"},
MiniStatuslineInactive = {fg = "#896C7D", bg = "#261720"},
MiniStatuslineModeCommand = {fg = "#261720", bg = "#8DAFE2", bold = true},
MiniStatuslineModeInsert = {fg = "#261720", bg = "#EFD2E3", bold = true},
MiniStatuslineModeNormal = {fg = "#EFD2E3", bg = "#5F4554", bold = true},
MiniStatuslineModeOther = {fg = "#261720", bg = "#D18DE2", bold = true},
MiniStatuslineModeReplace = {fg = "#261720", bg = "#D0435F", bold = true},
MiniStatuslineModeVisual = {fg = "#261720", bg = "#EA86C2", bold = true},
MiniTablineVisible = {fg = "#E28D8D", bg = "#331F2B"},
ModeMsg = {fg = "#EFD2E3", bold = true},
MoreMsg = {fg = "#D18DE2"},
MsgArea = {fg = "#EFD2E3"},
MsgSeparator = {fg = "#3F2735"},
NonText = {fg = "#896C7D"},
NormalFloat = {fg = "#EFD2E3", bg = "#331F2B"},
NormalNC = {fg = "#AD859D", bg = "#261720"},
["@lsp.type.number"] = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#EFD2E3"},
["@lsp.type.operator"] = {link = "Operator"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#EFD2E3", bg = "#331F2B"},
PmenuExtra = {fg = "#896C7D", bg = "#331F2B"},
PmenuExtraSel = {fg = "#AD859D", bg = "#3F2735"},
PmenuKind = {fg = "#D65C8D", bg = "#331F2B"},
PmenuKindSel = {fg = "#D65C8D", bg = "#3F2735", bold = true},
PmenuMatch = {fg = "#EA86C2", bold = true},
PmenuMatchSel = {fg = "#EA86C2", bold = true, underline = true},
PmenuSbar = {bg = "#3F2735"},
PmenuSel = {fg = "#EA86C2", bg = "#3F2735", bold = true},
PmenuThumb = {bg = "#5F4554"},
PreProc = {fg = "#8DAFE2"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@keyword.directive"] = {link = "PreProc"},
Question = {fg = "#8DAFE2"},
QuickFixLine = {bg = "#3F2735", bold = true},
["@keyword.repeat"] = {link = "Repeat"},
Search = {fg = "#E28D8D", bg = "#48323F"},
SignColumn = {bg = "#261720"},
Special = {fg = "#D65C8D"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
SpecialComment = {fg = "#AD859D", bold = true},
SpecialKey = {fg = "#896C7D"},
SpellBad = {fg = "#D0435F", undercurl = true},
SpellCap = {fg = "#E28D8D", undercurl = true},
SpellLocal = {fg = "#D18DE2", undercurl = true},
SpellRare = {fg = "#8DAFE2", undercurl = true},
Statement = {fg = "#8DAFE2", bold = true},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#EFD2E3", bg = "#3F2735"},
StatusLineNC = {fg = "#896C7D", bg = "#331F2B"},
["@lsp.type.string"] = {link = "String"},
["@string"] = {link = "String"},
["@lsp.type.struct"] = {link = "Structure"},
Substitute = {fg = "#261720", bg = "#8DAFE2"},
TabLine = {fg = "#896C7D", bg = "#331F2B"},
MiniTablineHidden = {link = "TabLine"},
TabLineFill = {bg = "#261720"},
TabLineSel = {fg = "#EA86C2", bg = "#3F2735", bold = true},
MiniTablineCurrent = {link = "TabLineSel"},
TermCursor = {fg = "#261720", bg = "#EA86C2"},
TermCursorNC = {fg = "#261720", bg = "#AD859D"},
Title = {fg = "#EA86C2", bold = true},
Todo = {fg = "#E28D8D", bold = true},
TroubleIndent = {fg = "#AD859D", bg = "#331F2B"},
TroublePos = {fg = "#AD859D", bg = "#331F2B"},
Type = {fg = "#D18DE2"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
["@lsp.type.class"] = {link = "Type"},
["@lsp.type.enum"] = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@type"] = {link = "Type"},
["@variable.parameter"] = {link = "Type"},
Typedef = {fg = "#D18DE2", italic = true},
["@lsp.type.interface"] = {link = "Typedef"},
["@lsp.type.typeParameter"] = {link = "Typedef"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
VertSplit = {fg = "#331F2B"},
Visual = {fg = "#261720", bg = "#EA86C2"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#E28D8D"},
Whitespace = {fg = "#3F2735"},
WildMenu = {fg = "#261720", bg = "#EFD2E3"},
WinBar = {fg = "#AD859D", bg = "#48323F"},
WinBarNC = {fg = "#896C7D", bg = "#48323F"},
WinSeparator = {fg = "#331F2B"},
markdownH1 = {fg = "#EA86C2", bold = true},
markdownH1Delimiter = {link = "markdownH1"},
markdownH2 = {fg = "#E28D8D", bold = true},
markdownH2Delimiter = {link = "markdownH2"},
markdownH3 = {fg = "#D18DE2", bold = true},
markdownH3Delimiter = {link = "markdownH3"},
markdownH4 = {fg = "#D65C8D", bold = true},
markdownH4Delimiter = {link = "markdownH4"},
markdownH5 = {fg = "#8DAFE2", bold = true},
markdownH5Delimiter = {link = "markdownH5"},
markdownH6 = {fg = "#D0435F", bold = true},
markdownH6Delimiter = {link = "markdownH6"},
["@attribute"] = {fg = "#E28D8D"},
["@attribute.builtin"] = {fg = "#E28D8D", bold = true, italic = true},
["@comment.documentation"] = {fg = "#AD859D", italic = true},
["@comment.error"] = {fg = "#D0435F", bold = true},
["@comment.note"] = {fg = "#8DAFE2", bold = true},
["@comment.todo"] = {fg = "#E28D8D", bold = true},
["@comment.warning"] = {fg = "#E28D8D", bold = true},
["@constant.builtin"] = {fg = "#D18DE2", bold = true, italic = true},
["@constructor"] = {fg = "#EA86C2"},
["@diff.delta"] = {fg = "#EA86C2"},
GitSignsChange = {link = "@diff.delta"},
["@diff.minus"] = {fg = "#D0435F"},
GitSignsDelete = {link = "@diff.minus"},
["@diff.plus"] = {fg = "#D18DE2"},
GitSignsAdd = {link = "@diff.plus"},
["@function.builtin"] = {fg = "#D65C8D", bold = true, italic = true},
["@keyword.function"] = {fg = "#8DAFE2", italic = true},
["@keyword.operator"] = {fg = "#8DAFE2"},
["@keyword.return"] = {fg = "#D0435F", italic = true},
["@label"] = {fg = "#8DAFE2"},
["@lsp.mod.defaultLibrary"] = {italic = true},
["@lsp.mod.deprecated"] = {fg = "#896C7D", strikethrough = true},
["@lsp.mod.readonly"] = {italic = true},
["@lsp.type.decorator"] = {fg = "#E28D8D"},
["@lsp.type.namespace"] = {fg = "#EFD2E3", italic = true},
["@lsp.type.parameter"] = {fg = "#D65C8D", italic = true},
["@lsp.type.property"] = {fg = "#EFD2E3"},
["@lsp.type.variable"] = {fg = "#EFD2E3"},
["@markup.heading"] = {fg = "#EA86C2", bold = true},
["@markup.heading.1"] = {fg = "#EA86C2", bg = "#5F354E", bold = true},
RenderMarkdownH1Bg = {link = "@markup.heading.1"},
["@markup.heading.2"] = {fg = "#E28D8D", bg = "#5C3838", bold = true},
RenderMarkdownH2Bg = {link = "@markup.heading.2"},
["@markup.heading.3"] = {fg = "#D18DE2", bg = "#55385C", bold = true},
RenderMarkdownH3Bg = {link = "@markup.heading.3"},
["@markup.heading.4"] = {fg = "#D65C8D", bg = "#4C2F3A", bold = true},
RenderMarkdownH4Bg = {link = "@markup.heading.4"},
["@markup.heading.5"] = {fg = "#8DAFE2", bg = "#38465C", bold = true},
RenderMarkdownH5Bg = {link = "@markup.heading.5"},
["@markup.heading.6"] = {fg = "#D0435F", bg = "#462B30", bold = true},
RenderMarkdownH6Bg = {link = "@markup.heading.6"},
["@markup.italic"] = {italic = true},
["@markup.link"] = {fg = "#8DAFE2", underline = true},
["@markup.link.label"] = {fg = "#EA86C2"},
["@markup.link.url"] = {fg = "#8DAFE2", italic = true, underline = true},
["@markup.list"] = {fg = "#E28D8D"},
["@markup.quote"] = {fg = "#AD859D", italic = true},
["@markup.raw"] = {fg = "#D18DE2"},
["@markup.raw.block"] = {fg = "#D18DE2"},
["@markup.strikethrough"] = {fg = "#896C7D", strikethrough = true},
["@markup.strong"] = {bold = true},
["@module"] = {fg = "#E28D8D"},
["@module.builtin"] = {fg = "#E28D8D", bold = true, italic = true},
["@property"] = {fg = "#EA86C2", italic = true},
["@punctuation.bracket"] = {fg = "#EFD2E3"},
["@punctuation.delimiter"] = {fg = "#896C7D"},
["@punctuation.special"] = {fg = "#EA86C2"},
["@string.escape"] = {fg = "#EA86C2"},
["@string.regexp"] = {fg = "#E28D8D"},
["@string.special"] = {fg = "#EA86C2"},
["@string.special.url"] = {fg = "#8DAFE2", underline = true},
["@tag"] = {fg = "#8DAFE2"},
["@tag.attribute"] = {fg = "#E28D8D"},
["@tag.builtin"] = {fg = "#8DAFE2", bold = true, italic = true},
["@tag.delimiter"] = {fg = "#896C7D"},
["@type.builtin"] = {fg = "#D18DE2", bold = true, italic = true},
["@variable"] = {fg = "#EFD2E3", italic = true},
["@variable.builtin"] = {fg = "#EA86C2", bold = true, italic = true},
["@variable.member"] = {fg = "#EFD2E3"},
  }
  return theme
end
return P
