local thrillerbark = {}
---@return table
function thrillerbark.get()
	return {
		["base"] = "#0c030a",
		["kuraigana"] = "#150a12",
		["cocoa"] = "#1c111a",
		["text"] = "#fec8d5",
		["wine"] = "#a5123e",
		["nagashidaru"] = "#6e0c2a",
		["mihawk"] = "#261722",
		["dracule"] = "#372a34",
		["coffin"] = "#160813",
		["blood"] = "#ed1d2e",
		["ruby"] = "#ff4c5b",
		["wonder"] = "#d573d9",
		["garden"] = "#f893fb",
		["sangria"] = "#ff5c74",
		["fruit"] = "#ff8093",
		["kumashi"] = "#8896c8",
		["sea"] = "#a9b7ea",
		["surprise"] = "#ff70b3",
		["zombie"] = "#ff94c6",
		["jam"] = "#d5396b",
		["berry"] = "#fa5c8e",
		["ghost"] = "#deafba",
		["hollow"] = "#fcd9e1",
		["b"] = "bold",
		["buc"] = "bold,undercurl",
		["bu"] = "bold,underline",
		["bui"] = "bold,underline,italic",
		["i"] = "italic",
		["nc"] = "nocombine",
		["na"] = "none",
		["rev"] = "reverse",
		["strike"] = "strikethrough",
		["u"] = "underline",
	}
end
return thrillerbark
