local lush = require('lush')
local hsl = lush.hsl

local thriller	= hsl(324, 30, 10)
local bark			= hsl(324, 30, 11)
local cocoa			= hsl(324, 30, 12)
local dracule		=	hsl(324, 36, 18)
local mihawk		= hsl(324, 36, 24)
local wine			= hsl(324, 36, 30)
local gecko			= hsl(324, 18, 48)
local moria			= hsl(324, 24, 60)
local negative	= hsl(324, 72, 84)
local hollow		= hsl(324, 72, 90)
local jewel			= hsl(340, 48, 36)
local berry			= hsl(340, 48, 48)
local jam				= hsl(340, 60, 60)
local surprise	= hsl(330, 84, 72)
local zombie		= hsl(330, 100, 80)
local kuma			= hsl(216, 60, 72)
local sea				= hsl(216, 84, 84)
local wonder		= hsl(291, 36, 54)
local garden		= hsl(303, 54, 72)
local sangria		= hsl(353, 74, 62)
local fruit			= hsl(353, 72, 72)
local blood			= hsl(347, 84, 36)
local ruby			= hsl(348, 72, 54)
local marimo		= hsl(154, 48, 54)
local santoryu	= hsl(154, 48, 72)

local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    ColorColumn    { bg = mihawk },
    Conceal        { fg = gecko },
    Cursor         { bg = negative, fg = cocoa },
    CurSearch      { bg = sea, fg = mihawk },
    lCursor        { Cursor },
    CursorIM       { Cursor },
    CursorColumn   { bg = dracule },
    CursorLine     { CursorColumn },
    Directory      { fg = jam },
    DiffAdd        { bg = santoryu, fg = cocoa, gui = "bold" },
    DiffChange     { bg = garden, fg = cocoa, gui = "bold" },
    DiffDelete     { bg = cocoa, fg = ruby, gui = "bold"},
    DiffText       { bg = kuma, fg = cocoa },
    EndOfBuffer    { fg = gecko },
    TermCursor     { bg = moria, fg = cocoa },
    TermCursorNC   { fg = moria },
    ErrorMsg       { bg = dracule, fg = ruby },
    VertSplit      { fg = dracule },
    Folded         { bg = bark, fg = negative },
    FoldColumn     { fg = wine },
    SignColumn     { bg = jewel },
    IncSearch      { CurSearch },
    Substitute     { fg = kuma, bg = wine },
    LineNr         { bg = berry, fg = thriller },
    LineNrAbove    { LineNr },
    LineNrBelow    { LineNr },
    CursorLineNr   { bg = dracule, fg = kuma, gui = "bold" },
    CursorLineFold { FoldColumn },
    CursorLineSign { FoldColumn },
    MatchParen     { bg = wine, fg = kuma, gui = "bold"},
    ModeMsg        { fg = negative, gui = "bold" },
    MsgArea        { fg = negative },
    MsgSeparator   { bg = moria, fg = cocoa },
    MoreMsg        { fg = wine },
    NonText        { fg = gecko },
    Normal         { bg = cocoa, fg = negative },
    NormalFloat    { bg = bark, fg = moria },
    FloatBorder    { NormalFloat },
    FloatTitle     { fg = negative, gui = "bold" },
    NormalNC       { fg = gecko },
    Pmenu          { bg = bark, fg = negative },
    PmenuSel       { bg = negative, fg = bark },
    PmenuKind      { Pmenu },
    PmenuKindSel   { PmenuSel },
    PmenuExtra     { Pmenu },
    PmenuExtraSel  { PmenuSel},
    PmenuSbar      { Pmenu },
    PmenuThumb     { bg = gecko, fg = hollow },
    Question       { fg = zombie },
    QuickFixLine   { Question },
    Search         { IncSearch },
    SpecialKey     { fg = moria },
    SpellBad       { fg = sangria, gui = "undercurl" },
    SpellCap       { fg = fruit, gui = "undercurl" },
    SpellLocal     { fg = marimo, gui = "undercurl" },
    SpellRare      { fg = sea, gui= "undercurl" },
    StatusLine     { bg = mihawk },
    StatusLineNC   { bg = dracule },
    TabLine        { bg = bark, fg = gecko },
    TabLineFill    { bg = thriller },
    TabLineSel     { bg = surprise, fg = cocoa, gui = "italic" },
    Title          { gui = "bold" },
    Visual         { bg = surprise, fg = cocoa },
    VisualNOS      { bg = berry, fg = cocoa },
    WarningMsg     { fg = fruit },
    Whitespace     { fg = wine },
    Winseparator   { VertSplit },
    WildMenu       { Cursor },
    WinBar         { bg = thriller, gui = "bold" },
    WinBarNC       { bg = thriller },

    Comment        { fg = gecko, gui = "italic" },

    Constant       { fg = marimo },
    String         { fg = zombie },
    Character      { fg = garden },
    Number         { Character },
    Boolean        { Character },
    Float          { Character },

    Identifier     { fg = jam },
    Function       { fg = kuma },

    Statement      { fg = sea, gui = "bold" },
    Conditional    { Statement },
    Repeat         { Statement },
    Label          { Statement },
    Operator       { fg = surprise },
    Keyword        { Statement },
    Exception      { Statement },

    PreProc        { fg = fruit },
    Include        { PreProc },
    Define         { PreProc },
    Macro          { PreProc },
    PreCondit      { PreProc },

    Type           { fg = surprise },
    StorageClass   { Type },
    Structure      { Type },
    Typedef        { Type },

    Special        { fg = kuma },
    SpecialChar    { fg = garden },
    Tag            { Special },
    Delimiter      { fg = surprise },
    SpecialComment { Special },
    Debug          { Special },

    Underlined     { gui = "underline" },
    Ignore         { fg = moria },
    Error          { bg = blood, fg = hollow },
    Todo           { gui = "bold" },

    LspReferenceText            { Visual },
    LspReferenceRead            { Visual },
    LspReferenceWrite           { Visual },
    LspCodeLens                 { Comment },
    LspCodeLensSeparator        { Comment },
    LspSignatureActiveParameter { Visual },

    DiagnosticError            { fg = blood },
    DiagnosticWarn             { fg = sangria },
    DiagnosticInfo             { fg = surprise },
    DiagnosticHint             { fg = kuma },
    DiagnosticOk               { fg = marimo },
    DiagnosticVirtualTextError { DiagnosticError },
    DiagnosticVirtualTextWarn  { DiagnosticWarn},
    DiagnosticVirtualTextInfo  { DiagnosticInfo },
    DiagnosticVirtualTextHint  { DiagnosticHint },
    DiagnosticVirtualTextOk    { DiagnosticOk },
    DiagnosticUnderlineError   { DiagnosticError, gui = "underline" },
    DiagnosticUnderlineWarn    { DiagnosticWarn, gui = "underline" },
    DiagnosticUnderlineInfo    { DiagnosticInfo, gui = "underline" },
    DiagnosticUnderlineHint    { DiagnosticHint, gui = "underline" },
    DiagnosticUnderlineOk      { DiagnosticOk, gui = "underline" },
    DiagnosticFloatingError    { DiagnosticError },
    DiagnosticFloatingWarn     { DiagnosticWarn },
    DiagnosticFloatingInfo     { DiagnosticInfo },
    DiagnosticFloatingHint     { DiagnosticHint } ,
    DiagnosticFloatingOk       { DiagnosticOk },
    DiagnosticSignError        { DiagnosticError },
    DiagnosticSignWarn         { DiagnosticWarn },
    DiagnosticSignInfo         { DiagnosticInfo },
    DiagnosticSignHint         { DiagnosticHint },
    DiagnosticSignOk           { DiagnosticOk},

    sym"@text.literal"      { Comment },
    sym"@text.reference"    { Identifier },
    sym"@text.title"        { Title },
    sym"@text.uri"          { Underlined },
    sym"@text.underline"    { Underlined },
    sym"@text.todo"         { Todo },
    sym"@comment"           { Comment },
    sym"@punctuation"       { Delimiter },
    sym"@constant"          { Constant },
    sym"@constant.builtin"  { Special },
    sym"@constant.macro"    { Define },
    sym"@define"            { Define },
    sym"@macro"             { Macro },
    sym"@string"            { String },
    sym"@string.escape"     { SpecialChar },
    sym"@string.special"    { SpecialChar },
    sym"@character"         { Character },
    sym"@character.special" { SpecialChar },
    sym"@number"            { Number },
    sym"@boolean"           { Boolean },
    sym"@float"             { Float },
    sym"@function"          { Function },
    sym"@function.builtin"  { Special },
    sym"@function.macro"    { Macro },
    sym"@parameter"         { Identifier },
    sym"@method"            { Function },
    sym"@field"             { Identifier },
    sym"@property"          { Identifier },
    sym"@constructor"       { Special },
    sym"@conditional"       { Conditional },
    sym"@repeat"            { Repeat },
    sym"@label"             { Label },
    sym"@operator"          { Operator },
    sym"@keyword"           { Keyword },
    sym"@exception"         { Exception },
    sym"@variable"          { Identifier },
    sym"@type"              { Type },
    sym"@storageclass"      { StorageClass },
    sym"@structure"         { Structure },
    sym"@namespace"         { Identifier },
    sym"@include"           { Include },
    sym"@preproc"           { PreProc },
    sym"@debug"             { Debug },
    sym"@tag"               { Tag },

		GitSignsAdd							{ fg = marimo },
		GitSignsChange					{ fg = wonder },
		GitSignsDelete					{ fg = ruby },
		MiniDiffSignAdd					{ fg = santoryu, gui = "italic" },
		MiniDiffSignChange			{ fg = garden, gui = "italic" },
		MiniDiffSignDelete			{ fg = ruby, gui = "italic" },
		MiniStatuslineModeNormal{ bg = jam, fg = cocoa },
		MiniStatuslineModeInsert{ bg = zombie, fg = mihawk },
		MiniStatuslineModeVisual{ bg = garden, fg = cocoa },
		MiniStatuslineModeReplace{ bg = ruby, fg = mihawk },
		MiniStatuslineModeCommand{ bg = sea, fg = mihawk },
		MiniStatuslineModeTerminal{ bg = fruit, fg = cocoa },
		MiniStatuslineDevinfo		{ bg = berry, fg = negative },
		MiniStatuslineFilename		{ bg = cocoa, fg = moria },
		MiniStatuslineFileinfo	{ MiniStatuslineDevinfo },
		MiniStatuslineInactive	{ bg = thriller, fg = gecko },
		MiniTablineCurrent			{ TabLineSel },
		MiniTablineVisible			{ fg = surprise, bg = wine },
		MiniTablineHidden				{ TabLine },
		MiniTablineModifiedCurrent { MiniTablineCurrent, gui = "bold_italic" },
		MiniTablineModifiedVisible { MiniTablineVisible, gui = "bold" },
		MiniTablineModifiedHidden { MiniTablineHidden, gui = "bold" },
		MiniTablineFill					{ TabLineFill },
		RenderMarkdownH1Bg			{ bg = dracule, fg = surprise },
		RenderMarkdownH2Bg			{ bg = dracule, fg = kuma },
		RenderMarkdownH3Bg			{ bg = dracule, fg = fruit },
		RenderMarkdownH4Bg			{ bg = dracule, fg = blood },
		RenderMarkdownH5Bg			{ bg = dracule, fg = marimo },
		RenderMarkdownH6Bg			{ bg = dracule, fg = wonder },
		TroubleIndent						{ bg = bark, fg = berry },
		TroublePos							{ bg = bark, fg = berry }
}
end)

return theme
