# perona v0.4.1 by sailorfe
# built 2026-03-04
# https://codeberg.org/sailorfe/perona.nvim

[colors]
foreground = "#EAC3DA"
background = "#261720"
cursor_bg = "#EAC3DA"
cursor_border = "#EAC3DA"
cursor_fg = "#261720"
selection_bg = "#ED82C2"
selection_fg = "#261720"
split = "#5F4554"
compose_cursor = "#E28D8D"
scrollbar_thumb = "#331F2B"

ansi = ["#3F2735", "#D0435F", "#D18DE2", "#E28D8D", "#8DAFE2", "#D65C8D", "#ED82C2", "#EAC3DA"]
brights = ["#5F4554", "#F76E89", "#E4A3F5", "#F5A3A3", "#A3C4F5", "#F075A6", "#FA9ED5", "#FFEBF7"]

[colors.tab_bar]
inactive_tab_edge = "#331F2B"
background = "#261720"

[colors.tab_bar.active_tab]
fg_color = "#261720"
bg_color = "#ED82C2"

[colors.tab_bar.inactive_tab]
fg_color = "#AD859D"
bg_color = "#3F2735"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#FA9ED5"
bg_color = "#3F2735"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#FA9ED5"
bg_color = "#261720"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#ED82C2"
bg_color = "#261720"

[metadata]
aliases = ['perona']
author = "sailorfe"
name = "Perona"
