# perona v0.4.1 by sailorfe
# built 2026-03-04
# https://codeberg.org/sailorfe/perona.nvim

[colors.primary]
background = "#261720"
foreground = "#EAC3DA"

[colors.normal]
black = "#331F2B"
red = "#D0435F"
green = "#D18DE2"
yellow = "#E28D8D"
blue = "#8DAFE2"
magenta = "#D65C8D"
cyan = "#ED82C2"
white = "#EAC3DA"

[colors.bright]
black = "#3F2735"
red = "#F76E89"
green = "#E4A3F5"
yellow = "#F5A3A3"
blue = "#A3C4F5"
magenta = "#F075A6"
cyan = "#FA9ED5"
white = "#FFEBF7"
