# -----------------------------------------------------------------------------
# Perona Alacritty Colors
# Theme: Perona
# Upstream: https://codeberg.org/spica/perona.nvim/src/branch/main/extras/alacritty/perona.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#281520'
foreground = '#f4b9dc'

#[colors.cursor]
#cursor = '#f4b9dc'
#text = '#281520'

# Normal colors
[colors.normal]
black = '#3c2031'
red = '#b31a3b'
green = '#b374be'
yellow = '#e65667'
blue = '#6a8cbe'
magenta = '#b54073'
cyan = '#e2509b'
white = '#d19ebd'

# Bright colors
[colors.bright]
black = '#633651'
red = '#d32246'
green = '#da95d5'
yellow = '#eb8490'
blue = '#9db2d2'
magenta = '#d65c8d'
cyan = '#f877b5'
white = '#f4b9dc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#70c2b1'

[[colors.indexed_colors]]
index = 17
color = '#f8d3e9'
