# Perona for Alacritty
# Author: sailorfe
# Upstream: https://codeberg.org/sailorfe/perona.nvim/src/branch/main/extras/alacritty/perona.toml

[colors.primary]
background = "#261720"
foreground = "#EFD2E3"

[colors.normal]
black = "#331F2B"
red   = "#D0435F"
green = "#D18DE2"
yellow = "#E28D8D"
blue  = "#8DAFE2"
magenta  = "#D65C8D"
cyan  = "#EA86C2"
white = "#EFD2E3"

[colors.bright]
black = "#3F2735"
red   = "#F76E89"
green = "#E4A3F5"
yellow = "#F5A3A3"
blue  = "#A3C4F5"
magenta  = "#F76EA5"
cyan  = "#FBB1DE"
white = "#FFEBF7"