# -----------------------------------------------------------------------------
# Perona Alacritty Colors
# Theme: Perona
# Upstream: https://codeberg.org/spica/perona.nvim/src/branch/main/extras/alacritty/perona.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#2c1b25'
foreground = '#efd2e3'

[colors.cursor]
cursor = '#efd2e3'
text = '#2c1b25'

# Normal colors
[colors.normal]
black = '#392330'
red = '#c4314e'
green = '#d18de2'
yellow = '#e28d8d'
blue = '#8dafe2'
magenta = '#d65c8d'
cyan = '#eb84c2'
white = '#efd2e3'

# Bright colors
[colors.bright]
black = '#462b3b'
red = '#e2506d'
green = '#ebb4f8'
yellow = '#f8b4b4'
blue = '#b4cff8'
magenta = '#f47cac'
cyan = '#f8b4dd'
white = '#ffebf7'
