# -----------------------------------------------------------------------------
# Perona Alacritty Colors
# Theme: Perona
# Upstream: https://codeberg.org/spica/perona.nvim/src/branch/main/extras/alacritty/perona.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#281520'
foreground = '#f4b9dc'

#[colors.cursor]
#cursor = '#f4b9dc'
#text = '#281520'

# Normal colors
[colors.normal]
black = '#3e1d31'
red = '#a90f30'
green = '#a75fb4'
yellow = '#e65667'
blue = '#8dafe2'
magenta = '#b54067'
cyan = '#f269ad'
white = '#b1819e'

# Bright colors
[colors.bright]
black = '#683152'
red = '#de3557'
green = '#de91da'
yellow = '#eb8490'
blue = '#b4cff8'
magenta = '#d65c85'
cyan = '#ff99cc'
white = '#f4b9dc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#74be9e'

[[colors.indexed_colors]]
index = 17
color = '#f8d3e9'
