# -----------------------------------------------------------------------------
# Perona Alacritty Colors
# Theme: Perona
# Upstream: https://codeberg.org/sailorfe/perona.nvim/src/branch/main/extras/alacritty/perona.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#281520'
foreground = '#f4b9dc'

#[colors.cursor]
#cursor = '#f4b9dc'
#text = '#281520'

# Normal colors
[colors.normal]
black = '#3e1d31'
red = '#c4314e'
green = '#bb68ca'
yellow = '#d65c5c'
blue = '#5c8dd6'
magenta = '#b54067'
cyan = '#f269ad'
white = '#b1819e'

# Bright colors
[colors.bright]
black = '#683152'
red = '#e2506d'
green = '#e28dde'
yellow = '#eb8484'
blue = '#8dafe2'
magenta = '#d65c85'
cyan = '#ff99cc'
white = '#f4b9dc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#74be9e'

[[colors.indexed_colors]]
index = 17
color = '#f8d3e9'
