# perona theme for spotify_player
# https://codeberg.org/spica/peronan.nvim

[[themes]]
name = "perona"
[themes.palette]
background = "#1b0e16"
foreground = "#e2accc"
black = "#281520"
blue = "#6a8cbe"
cyan = "#f877b5"
green = "#b374be"
magenta = "#d65c8d"
red = "#d32246"
white = "#e2accc"
yellow = "#eb8490"

[themes.component_style]
selection = { bg = "#351d2b", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow", modifiers = ["Italic"] }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "White" }

