# perona theme for spotify_player
# https://codeberg.org/spica/perona.nvim/src/branch/dev/extras/spotify_player

[[themes]]
name = "perona"
[themes.palette]
background = "#281520"
foreground = "#f4b9dc"
black = "#3e1d31"
blue = "#b4cff8"
cyan = "#ff99cc"
green = "#de91da"
magenta = "#d65c95"
red = "#de3557"
white = "#f4b9dc"
yellow = "#eb8490"

[themes.component_style]
selection = { bg = "#683152", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow", modifiers = ["Italic"] }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "Black", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "White" }

