#-*- perona

[colors]
foreground= efd2e3
background= 261720
selection-background=   ea86c2
selection-foreground=   261720
urls=		8dafe2
flash=	e28d8d

regular0=   331f2b
regular1=   d0435f
regular2=   d18de2
regular3=   e28d8d
regular4=		8dafe2
regular5=   d65c8d
regular6=   ea86c2
regular7=		efd2e3

bright0=		3f2735
bright1=    f76e89
bright2=    e4a3f5
bright3=    f5a3a3
bright4=    a3c4f5
bright5=    f76ea5
bright6=    fbb1de
bright7=    ffebf7
