#-*- perona

[colors]
foreground= efd2e3
background= 261720
selection-background=   e28dc0
selection-foreground=   261720
urls=		8dafe2
flash=	e28d8d

regular0=   331f2b
regular1=   d0435f
regular2=   d18de2
regular3=   e28d8d
regular4=		8dafe2
regular5=   d65c8d
regular6=   e28dc0
regular7=		efd2e3

bright0=		3f2735
bright1=    f47c94
bright2=    ebb4f8
bright3=    f8b4b4
bright4=    b4cff8
bright5=    f47cac
bright6=    f4b9dc
bright7=    ffebf7
