# perona v0.4.1 by sailorfe
# built 2026-03-04
# https://codeberg.org/sailorfe/perona.nvim

[colors]
foreground=EAC3DA
background=261720
selection-background=ED82C2
selection-foreground=261720
urls=8DAFE2
flash=ED82C2

regular0=3F2735
regular1=D0435F
regular2=D18DE2
regular3=E28D8D
regular4=8DAFE2
regular5=D65C8D
regular6=ED82C2
regular7=EAC3DA

bright0=5F4554
bright1=F76E89
bright2=E4A3F5
bright3=F5A3A3
bright4=A3C4F5
bright5=F075A6
bright6=FA9ED5
bright7=FFEBF7
