# perona v0.4.1 by sailorfe
# built 2026-03-04
# https://codeberg.org/sailorfe/perona.nvim

if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0261720"
    echo -en "\x1b]P1D0435F"
    echo -en "\x1b]P2D18DE2"
    echo -en "\x1b]P3E28D8D"
    echo -en "\x1b]P48DAFE2"
    echo -en "\x1b]P5D65C8D"
    echo -en "\x1b]P6ED82C2"
    echo -en "\x1b]P7EAC3DA"
    echo -en "\x1b]P83F2735"
    echo -en "\x1b]P9F76E89"
    echo -en "\x1b]PAE4A3F5"
    echo -en "\x1b]PBF5A3A3"
    echo -en "\x1b]PCA3C4F5"
    echo -en "\x1b]PDF075A6"
    echo -en "\x1b]PEFA9ED5"
    echo -en "\x1b]PFFFEBF7"
    clear
fi
