[colors.primary]
background = "[[base]]"
foreground = "[[text]]"

[colors.normal]
black = "[[surface]]"
red = "[[mihawk]]"
green = "[[garden]]"
yellow = "[[sangria]]"
blue = "[[kumashi]]"
magenta = "[[zombie]]"
cyan = "[[hollow]]"
white = "[[text]]"

[colors.bright]
black = "[[overlay]]"
red = "[[dracule]]"
green = "[[wonder]]"
yellow = "[[fruit]]"
blue = "[[beary]]"
magenta = "[[surprise]]"
cyan = "[[negative]]"
white = "[[light]]"
