background: [[base]]
foreground: [[text]]

color0: [[overlay]]
color1: [[mihawk]]
color2: [[garden]]
color3: [[sangria]]
color4: [[kumashi]]
color5: [[zombie]]
color6: [[hollow]]
color7: [[text]]

color8: [[high]]
color9: [[dracule]]
color10: [[wonder]]
color11: [[fruit]]
color12: [[beary]]
color13: [[surprise]]
color14: [[negative]]
color15: [[light]]
