# Perona for Termux
# Author: sailorfe
# Upstream: https://codeberg.org/sailorfe/perona.nvim/src/branch/main/extras/termux/perona.properties

background: [[base]]
foreground: [[text]]

color0: [[surface]]
color1: [[mihawk]]
color2: [[garden]]
color3: [[sangria]]
color4: [[kumashi]]
color5: [[zombie]]
color6: [[hollow]]
color7: [[text]]

color8: [[overlay]]
color9: [[dracule]]
color10: [[wonder]]
color11: [[fruit]]
color12: [[beary]]
color13: [[surprise]]
color14: [[negative]]
color15: [[light]]
