# -*- perona tty colors -*-

if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0{{base}}"
    echo -en "\x1b]P1{{mihawk}}"
    echo -en "\x1b]P2{{garden}}"
    echo -en "\x1b]P3{{sangria}}"
    echo -en "\x1b]P4{{kumashi}}"
    echo -en "\x1b]P5{{zombie}}"
    echo -en "\x1b]P6{{hollow}}"
    echo -en "\x1b]P7{{text}}"
    echo -en "\x1b]P8{{overlay}}"
    echo -en "\x1b]P9{{dracule}}"
    echo -en "\x1b]PA{{wonder}}"
    echo -en "\x1b]PB{{fruit}}"
    echo -en "\x1b]PC{{beary}}"
    echo -en "\x1b]PD{{surprise}}"
    echo -en "\x1b]PE{{negative}}"
    echo -en "\x1b]PF{{light}}"
    clear
fi
