[colors]
foreground = "[[text]]"
background = "[[base]]"
cursor_bg = "[[text]]"
cursor_border = "[[text]]"
cursor_fg = "[[base]]"
selection_bg = "[[hollow]]"
selection_fg = "[[base]]"
split = "[[high]]"
compose_cursor = "[[sangria]]"
scrollbar_thumb = "[[surface]]"

ansi = ["[[surface]]", "[[mihawk]]", "[[garden]]", "[[sangria]]", "[[kumashi]]", "[[zombie]]", "[[hollow]]", "[[text]]"]
brights = ["[[overlay]]", "[[dracule]]", "[[wonder]]", "[[fruit]]", "[[beary]]", "[[surprise]]", "[[negative]]", "[[light]]"]

[colors.tab_bar]
inactive_tab_edge = "[[surface]]"
background = "[[base]]"

[colors.tab_bar.active_tab]
fg_color = "[[base]]"
bg_color = "[[hollow]]"

[colors.tab_bar.inactive_tab]
fg_color = "[[faint]]"
bg_color = "[[overlay]]"

[colors.tab_bar.inactive_tab_hover]
fg_color = "[[negative]]"
bg_color = "[[overlay]]"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "[[negative]]"
bg_color = "[[base]]"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "[[hollow]]"
bg_color = "[[base]]"

[metadata]
aliases = ['perona']
author = "sailorfe"
name = "Perona"
