# Perona for Termux
# Author: sailorfe
# Upstream: https://codeberg.org/sailorfe/perona.nvim/src/branch/main/extras/termux/perona.properties

background: #261720
foreground: #EFD2E3

color0: #331F2B
color1: #D0435F
color2: #D18DE2
color3: #E28D8D
color4: #8DAFE2
color5: #D65C8D
color6: #EA86C2
color7: #EFD2E3

color8: #3F2735
color9: #F76E89
color10: #E4A3F5
color11: #F5A3A3
color12: #A3C4F5
color13: #F76EA5
color14: #FBB1DE
color15: #FFEBF7